#+html: <h1 align="center">org-roam-learn</h1>

* Installation
If you use quelpa, you can install it directly from source:

#+begin_src emacs-lisp
(use-package org-roam-learn
  :quelpa (org-roam-learn :fetcher github
                          :repo "domse007/org-roam-learn")
  :config
  (org-roam-learn-init))
#+end_src

* Customization
The package can be customized through the following variables:
- =org-roam-learn-selector=: This is a function which takes a list of
  =org-roam-learn-node=. The function should calculate a node of the
  list, which should be learned. The function must return the node,
  which should be learned. The function must only use the getters of
  the struct. A very rudimentary example:
  
  #+begin_src emacs-lisp
(setq org-roam-learn-selector (lambda (l) (car l)))
  #+end_src

- =org-roam-learn-db-file=: This is the path, where the database is
  saved. Example:

  #+begin_src emacs-lisp
(setq org-roam-learn-db-file (expand-file-name "custom/path/to.db"
					        user-emacs-directory))
  #+end_src

* Usage
- =org-roam-learn-add=: Add a node to the db.
- =org-roam-learn-learn=: Interactively select a tag and learn one of
  its nodes.
- =org-roam-learn-next=: Interactively show the next node to learn. This
  uses the last selected tag by =org-roam-learn-learn=.
- =org-roam-learn-exit=: Close the db. To use the package again call
  =org-roam-learn-init=.
